[env]
VERSION = { script = [
  "awk -F ' = ' '$1 ~ /version/ { gsub(/[\\\"]/, \"\", $2); printf(\"%s\",$2) }' Cargo.toml",
] }

[env.development]
RUST_LOG = { value = "tetanes=debug", condition = { env_not_set = ["RUST_LOG"] } }

[env.production]
RUST_LOG = { value = "tetanes=info", condition = { env_not_set = ["RUST_LOG"] } }

[tasks.default]
alias = "run"

[tasks.version]
description = "Print the crate version"
category = "Tools"
workspace = false
script = ["echo Version: ${VERSION}"]

[tasks.clean]
description = "Clean up build artifacts"
category = "Development"
workspace = false
command = "cargo"
args = ["clean"]

[tasks.lint]
description = "Lint with clippy"
category = "Development"
workspace = false
command = "cargo"
args = ["clippy"]

[tasks.build]
description = "Build TetaNES"
category = "Build"
workspace = false
command = "cargo"
args = ["build", "-p", "tetanes", "--profile", "dist", "${@}"]

[tasks.post-build]
description = "Strip symbols"
category = "Build"
workspace = false
command = "strip"
args = ["${CARGO_TARGET_DIR}/release/tetanes*"]

[tasks.run]
description = "Run TetaNES in release mode"
category = "Development"
workspace = false
command = "cargo"
args = ["run", "-p", "tetanes", "--release", "${@}"]

[tasks.profile]
description = "Run TetaNES in release mode w/profiling"
category = "Development"
workspace = false
command = "cargo"
args = ["run", "-p", "tetanes", "--release", "--features", "profiling", "${@}"]

[tasks.dev]
description = "Run TetaNES in development mode"
category = "Development"
workspace = false
command = "cargo"
args = ["run", "-p", "tetanes", "${@}"]

[tasks.install-web-deps]
description = "Install wasm target"
workspace = false
command = "rustup"
args = ["target", "add", "wasm32-unknown-unknown"]

[tasks.build-web]
description = "Build TetaNES Web"
category = "Build"
workspace = false
command = "trunk"
args = ["build", "--release"]
dependencies = ["install-web-deps"]

[tasks.run-web]
description = "Run TetaNES Web in release mode"
category = "Development"
workspace = false
command = "trunk"
args = ["serve", "--release"]
dependencies = ["install-web-deps"]

[tasks.dev-web]
description = "Run TetaNES Web in development mode"
category = "Development"
workspace = false
command = "trunk"
args = ["serve"]
dependencies = ["install-web-deps"]
