[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[config]
reduce_output = false
skip_core_tasks = true

[tasks.default]
alias = "run"

[tasks.version]
description = "Print the crate version"
category = "Tools"
workspace = false
script = ["echo Version: ${CARGO_MAKE_PROJECT_VERSION}"]

[tasks.clean]
description = "Clean up build artifacts"
category = "Development"
workspace = false
command = "cargo"
args = ["clean"]

[tasks.lint]
description = "Lint with clippy"
category = "Development"
workspace = false
command = "cargo"
args = ["clippy"]

[tasks.build]
description = "Build TetaNES"
category = "Build"
workspace = false
command = "cargo"
args = ["build", "-p", "tetanes", "--profile", "dist", "${@}"]

[tasks.bench]
description = "Benchmark TetaNES"
category = "Development"
workspace = false
command = "cargo"
args = ["bench", "--bench", "clock_frame", "${@}"]

[tasks.run]
description = "Run TetaNES in release mode"
category = "Development"
workspace = false
command = "cargo"
args = ["run", "-p", "tetanes", "--release", "${@}"]

[tasks.profile]
description = "Run TetaNES in release mode w/profiling"
category = "Development"
workspace = false
command = "cargo"
args = ["run", "-p", "tetanes", "--release", "--features", "profiling", "${@}"]

[tasks.dev]
description = "Run TetaNES in development mode"
category = "Development"
workspace = false
command = "cargo"
args = ["run", "-p", "tetanes", "${@}"]

[tasks.install-web-deps]
description = "Install wasm target"
category = "Development"
workspace = false
command = "rustup"
args = ["target", "add", "wasm32-unknown-unknown"]

[tasks.build-web]
description = "Build TetaNES Web"
category = "Build"
workspace = false
command = "trunk"
args = ["build", "--config", "tetanes/Cargo.toml", "--release", "--dist", "dist/web"]
dependencies = ["install-web-deps"]

[tasks.build-all]
run_task = { name = ["build", "build-web"] }

[tasks.run-web]
description = "Run TetaNES Web in release mode"
category = "Development"
workspace = false
command = "trunk"
args = ["serve", "--release", "--config", "tetanes/Cargo.toml"]
dependencies = ["install-web-deps"]

[tasks.profile-web]
description = "Run TetaNES Web in release mode w/profiling"
category = "Development"
workspace = false
command = "trunk"
args = ["serve", "--release", "--features", "profiling", "--config", "tetanes/Cargo.toml"]
dependencies = ["install-web-deps"]

[tasks.dev-web]
description = "Run TetaNES Web in development mode"
category = "Development"
workspace = false
command = "trunk"
args = ["serve", "--config", "tetanes/Cargo.toml"]
dependencies = ["install-web-deps"]
