#!/usr/bin/env bash

set -e
RUSTDOCFLAGS="-Dwarnings"
RUSTFLAGS="-Dwarnings"

echo '+cargo +nightly test'
cargo +nightly test

echo '+cargo +nightly test single_thread -- --test-threads=1 --ignored'
cargo +nightly test single_thread -- --test-threads=1 --ignored

echo '+cargo +nightly clippy --all-targets -- -D warnings'
cargo +nightly clippy --all-targets

echo '+cargo +nightly doc -- -D warnings'
cargo +nightly doc
