[package]
name = "tetanes-utils"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
readme.workspace = true
repository.workspace = true
homepage.workspace = true
publish = false

[lints]
workspace = true

[[bin]]
name = "list-boards"
test = false
bench = false

[[bin]]
name = "screenshot"
test = false
bench = false

[[bin]]
name = "chrdump"
test = false
bench = false

[[bin]]
name = "generate-db"
test = false
bench = false

[dependencies]
anyhow.workspace = true
clap.workspace = true
image.workspace = true
tetanes-core.workspace = true
