use super::*;

pub const CPU_FREQUENCY: u32 = 1_789_773;
pub const FRAME_COUNTER_RATE: f32 = CPU_FREQUENCY as f32 / 240.0;
pub const INES_FILE_MAGIC: u32 = 0x1a53_454e;
pub const PRG_ROM_SIZE: usize = 16384;
pub const RAM_SIZE: usize = 2048;
pub const SAMPLE_RATE: f32 = CPU_FREQUENCY as f32 / 44100.0 / 2.0;
pub const SRAM_SIZE: usize = 8192;
pub const LENGTH_TABLE: [u8; 32] = [
    10, 254, 20, 2, 40, 4, 80, 6, 160, 8, 60, 10, 14, 12, 26, 14, 12, 16, 24, 18, 48, 20, 96, 22,
    192, 24, 72, 26, 16, 28, 32, 30,
];
pub const DUTY_TABLE: [[u8; 8]; 4] = [
    [0, 1, 0, 0, 0, 0, 0, 0],
    [0, 1, 1, 0, 0, 0, 0, 0],
    [0, 1, 1, 1, 1, 0, 0, 0],
    [1, 0, 0, 1, 1, 1, 1, 1],
];
pub const TRIANGLE_TABLE: [u8; 32] = [
    15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,
    13, 14, 15,
];
pub const NOISE_TABLE: [u16; 16] = [
    4, 8, 16, 32, 64, 96, 128, 160, 202, 254, 380, 508, 762, 1016, 2034, 4068,
];
pub const DMC_TABLE: [u8; 16] = [
    214, 190, 170, 160, 143, 127, 113, 107, 95, 80, 71, 64, 53, 42, 36, 27,
];

/// System
///   BRK: Force Break
///   NOP: No Operation
///
/// Storage
///   LDA: Load A with M
///   LDX: Load X with M
///   LDY: Load Y with M
///   STA: Store A in M
///   STX: Store X in M
///   STY: Store Y in M
///   TAX: Transfer A to X
///   TAY: Transfer A to Y
///   TSX: Transfer Stack Pointer to X
///   TXA: Transfer X to A
///   TXS: Transfer X to Stack Pointer
///   TYA: Transfer Y to A
///
/// Arithmetic
///   ADC: Add M to A with Carry
///   DEC: Decrement M by One
///   DEX: Decrement X by One
///   DEY: Decrement Y by One
///   INC: Increment M by One
///   INX: Increment X by One
///   INY: Increment Y by One
///   SBC: Subtract M from A with Borrow
///
/// Bitwise
///   AND: "And" M with A
///   ASL: Shift Left One Bit (M or A)
///   BIT: Test Bits in M with A
///   EOR: "Exclusive-Or" M with A
///   LSR: Shift Right One Bit (M or A)
///   ORA: "OR" M with A
///   ROL: Rotate One Bit Left (M or A)
///   ROR: Rotate One Bit Right (M or A)
///
/// Branch
///   BCC: Branch on Carry Clear
///   BCS: Branch on Carry Set
///   BEQ: Branch on Result Zero
///   BMI: Branch on Result Minus
///   BNE: Branch on Result Not Zero
///   BPL: Branch on Result Plus
///   BVC: Branch on Overflow Clear
///   BVS: Branch on Overflow Set
///
/// Jump
///   JMP: Jump to Location
///   JSR: Jump to Location Save Return Address
///   RTI: Return from Interrupt
///   RTS: Return from Subroutine
///
/// Registers
///   CLC: Clear Carry Flag
///   CLD: Clear Decimal Mode
///   CLI: Clear Interrupt Disable Bit
///   CLV: Clear Overflow Flag
///   CMP: Compare M and A
///   CPX: Compare M and X
///   CPY: Compare M and Y
///   SEC: Set Carry Flag
///   SED: Set Decimal Mode
///   SEI: Set Interrupt Disable Status
///
/// Stack
///   PHA: Push A on Stack
///   PHP: Push Processor Status on Stack
///   PLA: Pull A from Stack
///   PLP: Pull Processor Status from Stack
///
/// Unofficial
///   KIL: Stop program counter
///   ANC: AND byte with accumulator
pub const INSTRUCTIONS: [Instruction; 1] = [
    Instruction {
        opcode: 0,
        name: "BRK",
        mode: AddrMode::Implied,
        size: 1,
        cycles: 7,
        page_cycles: 0,
        run: &Console::brk,
    },
    // Instruction {
    //     opcode: 1,
    //     name: "ORA",
    //     mode: AddrMode::IndexedIndirect,
    //     size: 2,
    //     cycles: 6,
    //     page_cycles: 0,
    //     run: CPU::ora,
    // },
    // Instruction {
    //     opcode: 2,
    //     name: "KIL",
    //     mode: AddrMode::Implied,
    //     size: 0,
    //     cycles: 2,
    //     page_cycles: 0,
    //     run: CPU::kil,
    // },
    // Instruction {
    //     opcode: 3,
    //     name: "SLO",
    //     mode: AddrMode::IndexedIndirect,
    //     size: 0,
    //     cycles: 8,
    //     page_cycles: 0,
    //     run: CPU::slo,
    // },
    // Instruction {
    //     opcode: 4,
    //     name: "NOP",
    //     mode: AddrMode::ZeroPage,
    //     size: 2,
    //     cycles: 3,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 5,
    //     name: "ORA",
    //     mode: AddrMode::ZeroPage,
    //     size: 2,
    //     cycles: 3,
    //     page_cycles: 0,
    //     run: CPU::ora,
    // },
    // Instruction {
    //     opcode: 6,
    //     name: "ASL",
    //     mode: AddrMode::ZeroPage,
    //     size: 2,
    //     cycles: 5,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 7,
    //     name: "SLO",
    //     mode: AddrMode::ZeroPage,
    //     size: 0,
    //     cycles: 5,
    //     page_cycles: 0,
    //     run: CPU::slo,
    // },
    // Instruction {
    //     opcode: 8,
    //     name: "PHP",
    //     mode: AddrMode::Implied,
    //     size: 1,
    //     cycles: 3,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 9,
    //     name: "ORA",
    //     mode: AddrMode::Immediate,
    //     size: 2,
    //     cycles: 2,
    //     page_cycles: 0,
    //     run: CPU::ora,
    // },
    // Instruction {
    //     opcode: 10,
    //     name: "ASL",
    //     mode: AddrMode::Accumulator,
    //     size: 1,
    //     cycles: 2,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 11,
    //     name: "ANC",
    //     mode: AddrMode::Immediate,
    //     size: 0,
    //     cycles: 2,
    //     page_cycles: 0,
    //     run: CPU::anc,
    // },
    // Instruction {
    //     opcode: 12,
    //     name: "NOP",
    //     mode: AddrMode::Absolute,
    //     size: 3,
    //     cycles: 4,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 13,
    //     name: "ORA",
    //     mode: AddrMode::Absolute,
    //     size: 3,
    //     cycles: 4,
    //     page_cycles: 0,
    //     run: CPU::ora,
    // },
    // Instruction {
    //     opcode: 14,
    //     name: "ASL",
    //     mode: AddrMode::Absolute,
    //     size: 3,
    //     cycles: 6,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 15,
    //     name: "SLO",
    //     mode: AddrMode::Absolute,
    //     size: 0,
    //     cycles: 6,
    //     page_cycles: 0,
    //     run: CPU::slo,
    // },
    // Instruction {
    //     opcode: 16,
    //     name: "BPL",
    //     mode: AddrMode::Relative,
    //     size: 2,
    //     cycles: 2,
    //     page_cycles: 1,
    // },
    // Instruction {
    //     opcode: 17,
    //     name: "ORA",
    //     mode: AddrMode::IndirectIndexed,
    //     size: 2,
    //     cycles: 5,
    //     page_cycles: 1,
    //     run: CPU::ora,
    // },
    // Instruction {
    //     opcode: 18,
    //     name: "KIL",
    //     mode: AddrMode::Implied,
    //     size: 0,
    //     cycles: 2,
    //     page_cycles: 0,
    //     run: CPU::kil,
    // },
    // Instruction {
    //     opcode: 19,
    //     name: "SLO",
    //     mode: AddrMode::IndirectIndexed,
    //     size: 0,
    //     cycles: 8,
    //     page_cycles: 0,
    //     run: CPU::slo,
    // },
    // Instruction {
    //     opcode: 20,
    //     name: "NOP",
    //     mode: AddrMode::ZeroPageX,
    //     size: 2,
    //     cycles: 4,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 21,
    //     name: "ORA",
    //     mode: AddrMode::ZeroPageX,
    //     size: 2,
    //     cycles: 4,
    //     page_cycles: 0,
    //     run: CPU::ora,
    // },
    // Instruction {
    //     opcode: 22,
    //     name: "ASL",
    //     mode: AddrMode::ZeroPageX,
    //     size: 2,
    //     cycles: 6,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 23,
    //     name: "SLO",
    //     mode: AddrMode::ZeroPageX,
    //     size: 0,
    //     cycles: 6,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 24,
    //     name: "CLC",
    //     mode: AddrMode::Implied,
    //     size: 1,
    //     cycles: 2,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 25,
    //     name: "ORA",
    //     mode: AddrMode::AbsoluteY,
    //     size: 3,
    //     cycles: 4,
    //     page_cycles: 1,
    //     run: CPU::ora,
    // },
    // Instruction {
    //     opcode: 26,
    //     name: "NOP",
    //     mode: AddrMode::Implied,
    //     size: 1,
    //     cycles: 2,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 27,
    //     name: "SLO",
    //     mode: AddrMode::AbsoluteY,
    //     size: 0,
    //     cycles: 7,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 28,
    //     name: "NOP",
    //     mode: AddrMode::AbsoluteX,
    //     size: 3,
    //     cycles: 4,
    //     page_cycles: 1,
    // },
    // Instruction {
    //     opcode: 29,
    //     name: "ORA",
    //     mode: AddrMode::AbsoluteX,
    //     size: 3,
    //     cycles: 4,
    //     page_cycles: 1,
    //     run: CPU::ora,
    // },
    // Instruction {
    //     opcode: 30,
    //     name: "ASL",
    //     mode: AddrMode::AbsoluteX,
    //     size: 3,
    //     cycles: 7,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 31,
    //     name: "SLO",
    //     mode: AddrMode::AbsoluteX,
    //     size: 0,
    //     cycles: 7,
    //     page_cycles: 0,
    //     run: CPU::slo,
    // },
    // Instruction {
    //     opcode: 32,
    //     name: "JSR",
    //     mode: AddrMode::Absolute,
    //     size: 3,
    //     cycles: 6,
    //     page_cycles: 0,
    //     run: CPU::jsr,
    // },
    // Instruction {
    //     opcode: 33,
    //     name: "AND",
    //     mode: AddrMode::IndexedIndirect,
    //     size: 2,
    //     cycles: 6,
    //     page_cycles: 0,
    //     run: CPU::and,
    // },
    // Instruction {
    //     opcode: 34,
    //     name: "KIL",
    //     mode: AddrMode::Implied,
    //     size: 0,
    //     cycles: 2,
    //     page_cycles: 0,
    //     run: CPU::kil,
    // },
    // Instruction {
    //     opcode: 35,
    //     name: "RLA",
    //     mode: AddrMode::IndexedIndirect,
    //     size: 0,
    //     cycles: 8,
    //     page_cycles: 0,
    //     run: CPU::rla,
    // },
    // Instruction {
    //     opcode: 36,
    //     name: "BIT",
    //     mode: AddrMode::ZeroPage,
    //     size: 2,
    //     cycles: 3,
    //     page_cycles: 0,
    //     run: CPU::bit,
    // },
    // Instruction {
    //     opcode: 37,
    //     name: "AND",
    //     mode: AddrMode::ZeroPage,
    //     size: 2,
    //     cycles: 3,
    //     page_cycles: 0,
    //     run: CPU::and,
    // },
    // Instruction {
    //     opcode: 38,
    //     name: "ROL",
    //     mode: AddrMode::ZeroPage,
    //     size: 2,
    //     cycles: 5,
    //     page_cycles: 0,
    //     run: CPU::rol,
    // },
    // Instruction {
    //     opcode: 39,
    //     name: "RLA",
    //     mode: AddrMode::ZeroPage,
    //     size: 0,
    //     cycles: 5,
    //     page_cycles: 0,
    //     run: CPU::rla,
    // },
    // Instruction {
    //     opcode: 40,
    //     name: "PLP",
    //     mode: AddrMode::Implied,
    //     size: 1,
    //     cycles: 4,
    //     page_cycles: 0,
    //     run: CPU::plp,
    // },
    // Instruction {
    //     opcode: 41,
    //     name: "AND",
    //     mode: AddrMode::Immediate,
    //     size: 2,
    //     cycles: 2,
    //     page_cycles: 0,
    //     run: CPU::and,
    // },
    // Instruction {
    //     opcode: 42,
    //     name: "ROL",
    //     mode: AddrMode::Accumulator,
    //     size: 1,
    //     cycles: 2,
    //     page_cycles: 0,
    //     run: CPU::rol,
    // },
    // Instruction {
    //     opcode: 43,
    //     name: "ANC",
    //     mode: AddrMode::Immediate,
    //     size: 0,
    //     cycles: 2,
    //     page_cycles: 0,
    //     run: CPU::anc,
    // },
    // Instruction {
    //     opcode: 44,
    //     name: "BIT",
    //     mode: AddrMode::Absolute,
    //     size: 3,
    //     cycles: 4,
    //     page_cycles: 0,
    //     run: CPU::bit,
    // },
    // Instruction {
    //     opcode: 45,
    //     name: "AND",
    //     mode: AddrMode::Absolute,
    //     size: 3,
    //     cycles: 4,
    //     page_cycles: 0,
    //     run: CPU::and,
    // },
    // Instruction {
    //     opcode: 46,
    //     name: "ROL",
    //     mode: AddrMode::Absolute,
    //     size: 3,
    //     cycles: 6,
    //     page_cycles: 0,
    //     run: CPU::rol,
    // },
    // Instruction {
    //     opcode: 47,
    //     name: "RLA",
    //     mode: AddrMode::Absolute,
    //     size: 0,
    //     cycles: 6,
    //     page_cycles: 0,
    //     run: CPU::rla,
    // },
    // Instruction {
    //     opcode: 48,
    //     name: "BMI",
    //     mode: AddrMode::Relative,
    //     size: 2,
    //     cycles: 2,
    //     page_cycles: 1,
    //     run: CPU::bmi,
    // },
    // Instruction {
    //     opcode: 49,
    //     name: "AND",
    //     mode: AddrMode::IndirectIndexed,
    //     size: 2,
    //     cycles: 5,
    //     page_cycles: 1,
    //     run: CPU::and,
    // },
    // Instruction {
    //     opcode: 50,
    //     name: "KIL",
    //     mode: AddrMode::Implied,
    //     size: 0,
    //     cycles: 2,
    //     page_cycles: 0,
    //     run: CPU::kil,
    // },
    // Instruction {
    //     opcode: 51,
    //     name: "RLA",
    //     mode: AddrMode::IndirectIndexed,
    //     size: 0,
    //     cycles: 8,
    //     page_cycles: 0,
    //     run: CPU::rla,
    // },
    // Instruction {
    //     opcode: 52,
    //     name: "NOP",
    //     mode: AddrMode::ZeroPageX,
    //     size: 2,
    //     cycles: 4,
    //     page_cycles: 0,
    //     run: CPU::nop,
    // },
    // Instruction {
    //     opcode: 53,
    //     name: "AND",
    //     mode: AddrMode::ZeroPageX,
    //     size: 2,
    //     cycles: 4,
    //     page_cycles: 0,
    //     run: CPU::and,
    // },
    // Instruction {
    //     opcode: 54,
    //     name: "ROL",
    //     mode: AddrMode::ZeroPageX,
    //     size: 2,
    //     cycles: 6,
    //     page_cycles: 0,
    //     run: CPU::rol,
    // },
    // Instruction {
    //     opcode: 55,
    //     name: "RLA",
    //     mode: AddrMode::ZeroPageX,
    //     size: 0,
    //     cycles: 6,
    //     page_cycles: 0,
    //     run: CPU::rla,
    // },
    // Instruction {
    //     opcode: 56,
    //     name: "SEC",
    //     mode: AddrMode::Implied,
    //     size: 1,
    //     cycles: 2,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 57,
    //     name: "AND",
    //     mode: AddrMode::AbsoluteY,
    //     size: 3,
    //     cycles: 4,
    //     page_cycles: 1,
    //     run: CPU::and,
    // },
    // Instruction {
    //     opcode: 58,
    //     name: "NOP",
    //     mode: AddrMode::Implied,
    //     size: 1,
    //     cycles: 2,
    //     page_cycles: 0,
    //     run: CPU::nop,
    // },
    // Instruction {
    //     opcode: 59,
    //     name: "RLA",
    //     mode: AddrMode::AbsoluteY,
    //     size: 0,
    //     cycles: 7,
    //     page_cycles: 0,
    //     run: CPU::rla,
    // },
    // Instruction {
    //     opcode: 60,
    //     name: "NOP",
    //     mode: AddrMode::AbsoluteX,
    //     size: 3,
    //     cycles: 4,
    //     page_cycles: 1,
    //     run: CPU::nop,
    // },
    // Instruction {
    //     opcode: 61,
    //     name: "AND",
    //     mode: AddrMode::AbsoluteX,
    //     size: 3,
    //     cycles: 4,
    //     page_cycles: 1,
    //     run: CPU::and,
    // },
    // Instruction {
    //     opcode: 62,
    //     name: "ROL",
    //     mode: AddrMode::AbsoluteX,
    //     size: 3,
    //     cycles: 7,
    //     page_cycles: 0,
    //     run: CPU::rol,
    // },
    // Instruction {
    //     opcode: 63,
    //     name: "RLA",
    //     mode: AddrMode::AbsoluteX,
    //     size: 0,
    //     cycles: 7,
    //     page_cycles: 0,
    //     run: CPU::rla,
    // },
    // Instruction {
    //     opcode: 64,
    //     name: "RTI",
    //     mode: AddrMode::Implied,
    //     size: 1,
    //     cycles: 6,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 65,
    //     name: "EOR",
    //     mode: AddrMode::IndexedIndirect,
    //     size: 2,
    //     cycles: 6,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 66,
    //     name: "KIL",
    //     mode: AddrMode::Implied,
    //     size: 0,
    //     cycles: 2,
    //     page_cycles: 0,
    //     run: CPU::kil,
    // },
    // Instruction {
    //     opcode: 67,
    //     name: "SRE",
    //     mode: AddrMode::IndexedIndirect,
    //     size: 0,
    //     cycles: 8,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 68,
    //     name: "NOP",
    //     mode: AddrMode::ZeroPage,
    //     size: 2,
    //     cycles: 3,
    //     page_cycles: 0,
    //     run: CPU::nop,
    // },
    // Instruction {
    //     opcode: 69,
    //     name: "EOR",
    //     mode: AddrMode::ZeroPage,
    //     size: 2,
    //     cycles: 3,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 70,
    //     name: "LSR",
    //     mode: AddrMode::ZeroPage,
    //     size: 2,
    //     cycles: 5,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 71,
    //     name: "SRE",
    //     mode: AddrMode::ZeroPage,
    //     size: 0,
    //     cycles: 5,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 72,
    //     name: "PHA",
    //     mode: AddrMode::Implied,
    //     size: 1,
    //     cycles: 3,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 73,
    //     name: "EOR",
    //     mode: AddrMode::Immediate,
    //     size: 2,
    //     cycles: 2,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 74,
    //     name: "LSR",
    //     mode: AddrMode::Accumulator,
    //     size: 1,
    //     cycles: 2,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 75,
    //     name: "ALR",
    //     mode: AddrMode::Immediate,
    //     size: 0,
    //     cycles: 2,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 76,
    //     name: "JMP",
    //     mode: AddrMode::Absolute,
    //     size: 3,
    //     cycles: 3,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 77,
    //     name: "EOR",
    //     mode: AddrMode::Absolute,
    //     size: 3,
    //     cycles: 4,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 78,
    //     name: "LSR",
    //     mode: AddrMode::Absolute,
    //     size: 3,
    //     cycles: 6,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 79,
    //     name: "SRE",
    //     mode: AddrMode::Absolute,
    //     size: 0,
    //     cycles: 6,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 80,
    //     name: "BVC",
    //     mode: AddrMode::Relative,
    //     size: 2,
    //     cycles: 2,
    //     page_cycles: 1,
    // },
    // Instruction {
    //     opcode: 81,
    //     name: "EOR",
    //     mode: AddrMode::IndirectIndexed,
    //     size: 2,
    //     cycles: 5,
    //     page_cycles: 1,
    // },
    // Instruction {
    //     opcode: 82,
    //     name: "KIL",
    //     mode: AddrMode::Implied,
    //     size: 0,
    //     cycles: 2,
    //     page_cycles: 0,
    //     run: CPU::kil,
    // },
    // Instruction {
    //     opcode: 83,
    //     name: "SRE",
    //     mode: AddrMode::IndirectIndexed,
    //     size: 0,
    //     cycles: 8,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 84,
    //     name: "NOP",
    //     mode: AddrMode::ZeroPageX,
    //     size: 2,
    //     cycles: 4,
    //     page_cycles: 0,
    //     run: CPU::nop,
    // },
    // Instruction {
    //     opcode: 85,
    //     name: "EOR",
    //     mode: AddrMode::ZeroPageX,
    //     size: 2,
    //     cycles: 4,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 86,
    //     name: "LSR",
    //     mode: AddrMode::ZeroPageX,
    //     size: 2,
    //     cycles: 6,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 87,
    //     name: "SRE",
    //     mode: AddrMode::ZeroPageX,
    //     size: 0,
    //     cycles: 6,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 88,
    //     name: "CLI",
    //     mode: AddrMode::Implied,
    //     size: 1,
    //     cycles: 2,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 89,
    //     name: "EOR",
    //     mode: AddrMode::AbsoluteY,
    //     size: 3,
    //     cycles: 4,
    //     page_cycles: 1,
    // },
    // Instruction {
    //     opcode: 90,
    //     name: "NOP",
    //     mode: AddrMode::Implied,
    //     size: 1,
    //     cycles: 2,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 91,
    //     name: "SRE",
    //     mode: AddrMode::AbsoluteY,
    //     size: 0,
    //     cycles: 7,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 92,
    //     name: "NOP",
    //     mode: AddrMode::AbsoluteX,
    //     size: 3,
    //     cycles: 4,
    //     page_cycles: 1,
    // },
    // Instruction {
    //     opcode: 93,
    //     name: "EOR",
    //     mode: AddrMode::AbsoluteX,
    //     size: 3,
    //     cycles: 4,
    //     page_cycles: 1,
    // },
    // Instruction {
    //     opcode: 94,
    //     name: "LSR",
    //     mode: AddrMode::AbsoluteX,
    //     size: 3,
    //     cycles: 7,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 95,
    //     name: "SRE",
    //     mode: AddrMode::AbsoluteX,
    //     size: 0,
    //     cycles: 7,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 96,
    //     name: "RTS",
    //     mode: AddrMode::Implied,
    //     size: 1,
    //     cycles: 6,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 97,
    //     name: "ADC",
    //     mode: AddrMode::IndexedIndirect,
    //     size: 2,
    //     cycles: 6,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 98,
    //     name: "KIL",
    //     mode: AddrMode::Implied,
    //     size: 0,
    //     cycles: 2,
    //     page_cycles: 0,
    //     run: CPU::kil,
    // },
    // Instruction {
    //     opcode: 99,
    //     name: "RRA",
    //     mode: AddrMode::IndexedIndirect,
    //     size: 0,
    //     cycles: 8,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 100,
    //     name: "NOP",
    //     mode: AddrMode::ZeroPage,
    //     size: 2,
    //     cycles: 3,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 101,
    //     name: "ADC",
    //     mode: AddrMode::ZeroPage,
    //     size: 2,
    //     cycles: 3,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 102,
    //     name: "ROR",
    //     mode: AddrMode::ZeroPage,
    //     size: 2,
    //     cycles: 5,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 103,
    //     name: "RRA",
    //     mode: AddrMode::ZeroPage,
    //     size: 0,
    //     cycles: 5,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 104,
    //     name: "PLA",
    //     mode: AddrMode::Implied,
    //     size: 1,
    //     cycles: 4,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 105,
    //     name: "ADC",
    //     mode: AddrMode::Immediate,
    //     size: 2,
    //     cycles: 2,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 106,
    //     name: "ROR",
    //     mode: AddrMode::Accumulator,
    //     size: 1,
    //     cycles: 2,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 107,
    //     name: "ARR",
    //     mode: AddrMode::Immediate,
    //     size: 0,
    //     cycles: 2,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 108,
    //     name: "JMP",
    //     mode: AddrMode::Indirect,
    //     size: 3,
    //     cycles: 5,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 109,
    //     name: "ADC",
    //     mode: AddrMode::Absolute,
    //     size: 3,
    //     cycles: 4,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 110,
    //     name: "ROR",
    //     mode: AddrMode::Absolute,
    //     size: 3,
    //     cycles: 6,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 111,
    //     name: "RRA",
    //     mode: AddrMode::Absolute,
    //     size: 0,
    //     cycles: 6,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 112,
    //     name: "BVS",
    //     mode: AddrMode::Relative,
    //     size: 2,
    //     cycles: 2,
    //     page_cycles: 1,
    // },
    // Instruction {
    //     opcode: 113,
    //     name: "ADC",
    //     mode: AddrMode::IndirectIndexed,
    //     size: 2,
    //     cycles: 5,
    //     page_cycles: 1,
    // },
    // Instruction {
    //     opcode: 114,
    //     name: "KIL",
    //     mode: AddrMode::Implied,
    //     size: 0,
    //     cycles: 2,
    //     page_cycles: 0,
    //     run: CPU::kil,
    // },
    // Instruction {
    //     opcode: 115,
    //     name: "RRA",
    //     mode: AddrMode::IndirectIndexed,
    //     size: 0,
    //     cycles: 8,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 116,
    //     name: "NOP",
    //     mode: AddrMode::ZeroPageX,
    //     size: 2,
    //     cycles: 4,
    //     page_cycles: 0,
    //     run: CPU::nop,
    // },
    // Instruction {
    //     opcode: 117,
    //     name: "ADC",
    //     mode: AddrMode::ZeroPageX,
    //     size: 2,
    //     cycles: 4,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 118,
    //     name: "ROR",
    //     mode: AddrMode::ZeroPageX,
    //     size: 2,
    //     cycles: 6,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 119,
    //     name: "RRA",
    //     mode: AddrMode::ZeroPageX,
    //     size: 0,
    //     cycles: 6,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 120,
    //     name: "SEI",
    //     mode: AddrMode::Implied,
    //     size: 1,
    //     cycles: 2,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 121,
    //     name: "ADC",
    //     mode: AddrMode::AbsoluteY,
    //     size: 3,
    //     cycles: 4,
    //     page_cycles: 1,
    // },
    // Instruction {
    //     opcode: 122,
    //     name: "NOP",
    //     mode: AddrMode::Implied,
    //     size: 1,
    //     cycles: 2,
    //     page_cycles: 0,
    //     run: CPU::nop,
    // },
    // Instruction {
    //     opcode: 123,
    //     name: "RRA",
    //     mode: AddrMode::AbsoluteY,
    //     size: 0,
    //     cycles: 7,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 124,
    //     name: "NOP",
    //     mode: AddrMode::AbsoluteX,
    //     size: 3,
    //     cycles: 4,
    //     page_cycles: 1,
    //     run: CPU::nop,
    // },
    // Instruction {
    //     opcode: 125,
    //     name: "ADC",
    //     mode: AddrMode::AbsoluteX,
    //     size: 3,
    //     cycles: 4,
    //     page_cycles: 1,
    // },
    // Instruction {
    //     opcode: 126,
    //     name: "ROR",
    //     mode: AddrMode::AbsoluteX,
    //     size: 3,
    //     cycles: 7,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 127,
    //     name: "RRA",
    //     mode: AddrMode::AbsoluteX,
    //     size: 0,
    //     cycles: 7,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 128,
    //     name: "NOP",
    //     mode: AddrMode::Immediate,
    //     size: 2,
    //     cycles: 2,
    //     page_cycles: 0,
    //     run: CPU::nop,
    // },
    // Instruction {
    //     opcode: 129,
    //     name: "STA",
    //     mode: AddrMode::IndexedIndirect,
    //     size: 2,
    //     cycles: 6,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 130,
    //     name: "NOP",
    //     mode: AddrMode::Immediate,
    //     size: 0,
    //     cycles: 2,
    //     page_cycles: 0,
    //     run: CPU::nop,
    // },
    // Instruction {
    //     opcode: 131,
    //     name: "SAX",
    //     mode: AddrMode::IndexedIndirect,
    //     size: 0,
    //     cycles: 6,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 132,
    //     name: "STY",
    //     mode: AddrMode::ZeroPage,
    //     size: 2,
    //     cycles: 3,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 133,
    //     name: "STA",
    //     mode: AddrMode::ZeroPage,
    //     size: 2,
    //     cycles: 3,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 134,
    //     name: "STX",
    //     mode: AddrMode::ZeroPage,
    //     size: 2,
    //     cycles: 3,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 135,
    //     name: "SAX",
    //     mode: AddrMode::ZeroPage,
    //     size: 0,
    //     cycles: 3,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 136,
    //     name: "DEY",
    //     mode: AddrMode::Implied,
    //     size: 1,
    //     cycles: 2,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 137,
    //     name: "NOP",
    //     mode: AddrMode::Immediate,
    //     size: 0,
    //     cycles: 2,
    //     page_cycles: 0,
    //     run: CPU::nop,
    // },
    // Instruction {
    //     opcode: 138,
    //     name: "TXA",
    //     mode: AddrMode::Implied,
    //     size: 1,
    //     cycles: 2,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 139,
    //     name: "XAA",
    //     mode: AddrMode::Immediate,
    //     size: 0,
    //     cycles: 2,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 140,
    //     name: "STY",
    //     mode: AddrMode::Absolute,
    //     size: 3,
    //     cycles: 4,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 141,
    //     name: "STA",
    //     mode: AddrMode::Absolute,
    //     size: 3,
    //     cycles: 4,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 142,
    //     name: "STX",
    //     mode: AddrMode::Absolute,
    //     size: 3,
    //     cycles: 4,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 143,
    //     name: "SAX",
    //     mode: AddrMode::Absolute,
    //     size: 0,
    //     cycles: 4,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 144,
    //     name: "BCC",
    //     mode: AddrMode::Relative,
    //     size: 2,
    //     cycles: 2,
    //     page_cycles: 1,
    // },
    // Instruction {
    //     opcode: 145,
    //     name: "STA",
    //     mode: AddrMode::IndirectIndexed,
    //     size: 2,
    //     cycles: 6,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 146,
    //     name: "KIL",
    //     mode: AddrMode::Implied,
    //     size: 0,
    //     cycles: 2,
    //     page_cycles: 0,
    //     run: CPU::kil,
    // },
    // Instruction {
    //     opcode: 147,
    //     name: "AHX",
    //     mode: AddrMode::IndirectIndexed,
    //     size: 0,
    //     cycles: 6,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 148,
    //     name: "STY",
    //     mode: AddrMode::ZeroPageX,
    //     size: 2,
    //     cycles: 4,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 149,
    //     name: "STA",
    //     mode: AddrMode::ZeroPageX,
    //     size: 2,
    //     cycles: 4,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 150,
    //     name: "STX",
    //     mode: AddrMode::ZeroPageY,
    //     size: 2,
    //     cycles: 4,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 151,
    //     name: "SAX",
    //     mode: AddrMode::ZeroPageY,
    //     size: 0,
    //     cycles: 4,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 152,
    //     name: "TYA",
    //     mode: AddrMode::Implied,
    //     size: 1,
    //     cycles: 2,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 153,
    //     name: "STA",
    //     mode: AddrMode::AbsoluteY,
    //     size: 3,
    //     cycles: 5,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 154,
    //     name: "TXS",
    //     mode: AddrMode::Implied,
    //     size: 1,
    //     cycles: 2,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 155,
    //     name: "TAS",
    //     mode: AddrMode::AbsoluteY,
    //     size: 0,
    //     cycles: 5,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 156,
    //     name: "SHY",
    //     mode: AddrMode::AbsoluteX,
    //     size: 0,
    //     cycles: 5,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 157,
    //     name: "STA",
    //     mode: AddrMode::AbsoluteX,
    //     size: 3,
    //     cycles: 5,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 158,
    //     name: "SHX",
    //     mode: AddrMode::AbsoluteY,
    //     size: 0,
    //     cycles: 5,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 159,
    //     name: "AHX",
    //     mode: AddrMode::AbsoluteY,
    //     size: 0,
    //     cycles: 5,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 160,
    //     name: "LDY",
    //     mode: AddrMode::Immediate,
    //     size: 2,
    //     cycles: 2,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 161,
    //     name: "LDA",
    //     mode: AddrMode::IndexedIndirect,
    //     size: 2,
    //     cycles: 6,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 162,
    //     name: "LDX",
    //     mode: AddrMode::Immediate,
    //     size: 2,
    //     cycles: 2,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 163,
    //     name: "LAX",
    //     mode: AddrMode::IndexedIndirect,
    //     size: 0,
    //     cycles: 6,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 164,
    //     name: "LDY",
    //     mode: AddrMode::ZeroPage,
    //     size: 2,
    //     cycles: 3,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 165,
    //     name: "LDA",
    //     mode: AddrMode::ZeroPage,
    //     size: 2,
    //     cycles: 3,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 166,
    //     name: "LDX",
    //     mode: AddrMode::ZeroPage,
    //     size: 2,
    //     cycles: 3,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 167,
    //     name: "LAX",
    //     mode: AddrMode::ZeroPage,
    //     size: 0,
    //     cycles: 3,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 168,
    //     name: "TAY",
    //     mode: AddrMode::Implied,
    //     size: 1,
    //     cycles: 2,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 169,
    //     name: "LDA",
    //     mode: AddrMode::Immediate,
    //     size: 2,
    //     cycles: 2,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 170,
    //     name: "TAX",
    //     mode: AddrMode::Implied,
    //     size: 1,
    //     cycles: 2,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 171,
    //     name: "LAX",
    //     mode: AddrMode::Immediate,
    //     size: 0,
    //     cycles: 2,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 172,
    //     name: "LDY",
    //     mode: AddrMode::Absolute,
    //     size: 3,
    //     cycles: 4,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 173,
    //     name: "LDA",
    //     mode: AddrMode::Absolute,
    //     size: 3,
    //     cycles: 4,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 174,
    //     name: "LDX",
    //     mode: AddrMode::Absolute,
    //     size: 3,
    //     cycles: 4,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 175,
    //     name: "LAX",
    //     mode: AddrMode::Absolute,
    //     size: 0,
    //     cycles: 4,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 176,
    //     name: "BCS",
    //     mode: AddrMode::Relative,
    //     size: 2,
    //     cycles: 2,
    //     page_cycles: 1,
    // },
    // Instruction {
    //     opcode: 177,
    //     name: "LDA",
    //     mode: AddrMode::IndirectIndexed,
    //     size: 2,
    //     cycles: 5,
    //     page_cycles: 1,
    // },
    // Instruction {
    //     opcode: 178,
    //     name: "KIL",
    //     mode: AddrMode::Implied,
    //     size: 0,
    //     cycles: 2,
    //     page_cycles: 0,
    //     run: CPU::kil,
    // },
    // Instruction {
    //     opcode: 179,
    //     name: "LAX",
    //     mode: AddrMode::IndirectIndexed,
    //     size: 0,
    //     cycles: 5,
    //     page_cycles: 1,
    // },
    // Instruction {
    //     opcode: 180,
    //     name: "LDY",
    //     mode: AddrMode::ZeroPageX,
    //     size: 2,
    //     cycles: 4,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 181,
    //     name: "LDA",
    //     mode: AddrMode::ZeroPageX,
    //     size: 2,
    //     cycles: 4,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 182,
    //     name: "LDX",
    //     mode: AddrMode::ZeroPageY,
    //     size: 2,
    //     cycles: 4,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 183,
    //     name: "LAX",
    //     mode: AddrMode::ZeroPageY,
    //     size: 0,
    //     cycles: 4,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 184,
    //     name: "CLV",
    //     mode: AddrMode::Implied,
    //     size: 1,
    //     cycles: 2,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 185,
    //     name: "LDA",
    //     mode: AddrMode::AbsoluteY,
    //     size: 3,
    //     cycles: 4,
    //     page_cycles: 1,
    // },
    // Instruction {
    //     opcode: 186,
    //     name: "TSX",
    //     mode: AddrMode::Implied,
    //     size: 1,
    //     cycles: 2,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 187,
    //     name: "LAS",
    //     mode: AddrMode::AbsoluteY,
    //     size: 0,
    //     cycles: 4,
    //     page_cycles: 1,
    // },
    // Instruction {
    //     opcode: 188,
    //     name: "LDY",
    //     mode: AddrMode::AbsoluteX,
    //     size: 3,
    //     cycles: 4,
    //     page_cycles: 1,
    // },
    // Instruction {
    //     opcode: 189,
    //     name: "LDA",
    //     mode: AddrMode::AbsoluteX,
    //     size: 3,
    //     cycles: 4,
    //     page_cycles: 1,
    // },
    // Instruction {
    //     opcode: 190,
    //     name: "LDX",
    //     mode: AddrMode::AbsoluteY,
    //     size: 3,
    //     cycles: 4,
    //     page_cycles: 1,
    // },
    // Instruction {
    //     opcode: 191,
    //     name: "LAX",
    //     mode: AddrMode::AbsoluteY,
    //     size: 0,
    //     cycles: 4,
    //     page_cycles: 1,
    // },
    // Instruction {
    //     opcode: 192,
    //     name: "CPY",
    //     mode: AddrMode::Immediate,
    //     size: 2,
    //     cycles: 2,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 193,
    //     name: "CMP",
    //     mode: AddrMode::IndexedIndirect,
    //     size: 2,
    //     cycles: 6,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 194,
    //     name: "NOP",
    //     mode: AddrMode::Immediate,
    //     size: 0,
    //     cycles: 2,
    //     page_cycles: 0,
    //     run: CPU::nop,
    // },
    // Instruction {
    //     opcode: 195,
    //     name: "DCP",
    //     mode: AddrMode::IndexedIndirect,
    //     size: 0,
    //     cycles: 8,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 196,
    //     name: "CPY",
    //     mode: AddrMode::ZeroPage,
    //     size: 2,
    //     cycles: 3,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 197,
    //     name: "CMP",
    //     mode: AddrMode::ZeroPage,
    //     size: 2,
    //     cycles: 3,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 198,
    //     name: "DEC",
    //     mode: AddrMode::ZeroPage,
    //     size: 2,
    //     cycles: 5,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 199,
    //     name: "DCP",
    //     mode: AddrMode::ZeroPage,
    //     size: 0,
    //     cycles: 5,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 200,
    //     name: "INY",
    //     mode: AddrMode::Implied,
    //     size: 1,
    //     cycles: 2,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 201,
    //     name: "CMP",
    //     mode: AddrMode::Immediate,
    //     size: 2,
    //     cycles: 2,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 202,
    //     name: "DEX",
    //     mode: AddrMode::Implied,
    //     size: 1,
    //     cycles: 2,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 203,
    //     name: "AXS",
    //     mode: AddrMode::Immediate,
    //     size: 0,
    //     cycles: 2,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 204,
    //     name: "CPY",
    //     mode: AddrMode::Absolute,
    //     size: 3,
    //     cycles: 4,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 205,
    //     name: "CMP",
    //     mode: AddrMode::Absolute,
    //     size: 3,
    //     cycles: 4,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 206,
    //     name: "DEC",
    //     mode: AddrMode::Absolute,
    //     size: 3,
    //     cycles: 6,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 207,
    //     name: "DCP",
    //     mode: AddrMode::Absolute,
    //     size: 0,
    //     cycles: 6,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 208,
    //     name: "BNE",
    //     mode: AddrMode::Relative,
    //     size: 2,
    //     cycles: 2,
    //     page_cycles: 1,
    // },
    // Instruction {
    //     opcode: 209,
    //     name: "CMP",
    //     mode: AddrMode::IndirectIndexed,
    //     size: 2,
    //     cycles: 5,
    //     page_cycles: 1,
    // },
    // Instruction {
    //     opcode: 210,
    //     name: "KIL",
    //     mode: AddrMode::Implied,
    //     size: 0,
    //     cycles: 2,
    //     page_cycles: 0,
    //     run: CPU::kil,
    // },
    // Instruction {
    //     opcode: 211,
    //     name: "DCP",
    //     mode: AddrMode::IndirectIndexed,
    //     size: 0,
    //     cycles: 8,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 212,
    //     name: "NOP",
    //     mode: AddrMode::ZeroPageX,
    //     size: 2,
    //     cycles: 4,
    //     page_cycles: 0,
    //     run: CPU::nop,
    // },
    // Instruction {
    //     opcode: 213,
    //     name: "CMP",
    //     mode: AddrMode::ZeroPageX,
    //     size: 2,
    //     cycles: 4,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 214,
    //     name: "DEC",
    //     mode: AddrMode::ZeroPageX,
    //     size: 2,
    //     cycles: 6,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 215,
    //     name: "DCP",
    //     mode: AddrMode::ZeroPageX,
    //     size: 0,
    //     cycles: 6,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 216,
    //     name: "CLD",
    //     mode: AddrMode::Implied,
    //     size: 1,
    //     cycles: 2,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 217,
    //     name: "CMP",
    //     mode: AddrMode::AbsoluteY,
    //     size: 3,
    //     cycles: 4,
    //     page_cycles: 1,
    // },
    // Instruction {
    //     opcode: 218,
    //     name: "NOP",
    //     mode: AddrMode::Implied,
    //     size: 1,
    //     cycles: 2,
    //     page_cycles: 0,
    //     run: CPU::nop,
    // },
    // Instruction {
    //     opcode: 219,
    //     name: "DCP",
    //     mode: AddrMode::AbsoluteY,
    //     size: 0,
    //     cycles: 7,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 220,
    //     name: "NOP",
    //     mode: AddrMode::AbsoluteX,
    //     size: 3,
    //     cycles: 4,
    //     page_cycles: 1,
    //     run: CPU::nop,
    // },
    // Instruction {
    //     opcode: 221,
    //     name: "CMP",
    //     mode: AddrMode::AbsoluteX,
    //     size: 3,
    //     cycles: 4,
    //     page_cycles: 1,
    // },
    // Instruction {
    //     opcode: 222,
    //     name: "DEC",
    //     mode: AddrMode::AbsoluteX,
    //     size: 3,
    //     cycles: 7,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 223,
    //     name: "DCP",
    //     mode: AddrMode::AbsoluteX,
    //     size: 0,
    //     cycles: 7,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 224,
    //     name: "CPX",
    //     mode: AddrMode::Immediate,
    //     size: 2,
    //     cycles: 2,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 225,
    //     name: "SBC",
    //     mode: AddrMode::IndexedIndirect,
    //     size: 2,
    //     cycles: 6,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 226,
    //     name: "NOP",
    //     mode: AddrMode::Immediate,
    //     size: 0,
    //     cycles: 2,
    //     page_cycles: 0,
    //     run: CPU::nop,
    // },
    // Instruction {
    //     opcode: 227,
    //     name: "ISC",
    //     mode: AddrMode::IndexedIndirect,
    //     size: 0,
    //     cycles: 8,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 228,
    //     name: "CPX",
    //     mode: AddrMode::ZeroPage,
    //     size: 2,
    //     cycles: 3,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 229,
    //     name: "SBC",
    //     mode: AddrMode::ZeroPage,
    //     size: 2,
    //     cycles: 3,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 230,
    //     name: "INC",
    //     mode: AddrMode::ZeroPage,
    //     size: 2,
    //     cycles: 5,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 231,
    //     name: "ISC",
    //     mode: AddrMode::ZeroPage,
    //     size: 0,
    //     cycles: 5,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 232,
    //     name: "INX",
    //     mode: AddrMode::Implied,
    //     size: 1,
    //     cycles: 2,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 233,
    //     name: "SBC",
    //     mode: AddrMode::Immediate,
    //     size: 2,
    //     cycles: 2,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 234,
    //     name: "NOP",
    //     mode: AddrMode::Implied,
    //     size: 1,
    //     cycles: 2,
    //     page_cycles: 0,
    //     run: CPU::nop,
    // },
    // Instruction {
    //     opcode: 235,
    //     name: "SBC",
    //     mode: AddrMode::Immediate,
    //     size: 0,
    //     cycles: 2,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 236,
    //     name: "CPX",
    //     mode: AddrMode::Absolute,
    //     size: 3,
    //     cycles: 4,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 237,
    //     name: "SBC",
    //     mode: AddrMode::Absolute,
    //     size: 3,
    //     cycles: 4,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 238,
    //     name: "INC",
    //     mode: AddrMode::Absolute,
    //     size: 3,
    //     cycles: 6,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 239,
    //     name: "ISC",
    //     mode: AddrMode::Absolute,
    //     size: 0,
    //     cycles: 6,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 240,
    //     name: "BEQ",
    //     mode: AddrMode::Relative,
    //     size: 2,
    //     cycles: 2,
    //     page_cycles: 1,
    // },
    // Instruction {
    //     opcode: 241,
    //     name: "SBC",
    //     mode: AddrMode::IndirectIndexed,
    //     size: 2,
    //     cycles: 5,
    //     page_cycles: 1,
    // },
    // Instruction {
    //     opcode: 242,
    //     name: "KIL",
    //     mode: AddrMode::Implied,
    //     size: 0,
    //     cycles: 2,
    //     page_cycles: 0,
    //     run: CPU::kil,
    // },
    // Instruction {
    //     opcode: 243,
    //     name: "ISC",
    //     mode: AddrMode::IndirectIndexed,
    //     size: 0,
    //     cycles: 8,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 244,
    //     name: "NOP",
    //     mode: AddrMode::ZeroPageX,
    //     size: 2,
    //     cycles: 4,
    //     page_cycles: 0,
    //     run: CPU::nop,
    // },
    // Instruction {
    //     opcode: 245,
    //     name: "SBC",
    //     mode: AddrMode::ZeroPageX,
    //     size: 2,
    //     cycles: 4,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 246,
    //     name: "INC",
    //     mode: AddrMode::ZeroPageX,
    //     size: 2,
    //     cycles: 6,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 247,
    //     name: "ISC",
    //     mode: AddrMode::ZeroPageX,
    //     size: 0,
    //     cycles: 6,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 248,
    //     name: "SED",
    //     mode: AddrMode::Implied,
    //     size: 1,
    //     cycles: 2,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 249,
    //     name: "SBC",
    //     mode: AddrMode::AbsoluteY,
    //     size: 3,
    //     cycles: 4,
    //     page_cycles: 1,
    // },
    // Instruction {
    //     opcode: 250,
    //     name: "NOP",
    //     mode: AddrMode::Implied,
    //     size: 1,
    //     cycles: 2,
    //     page_cycles: 0,
    //     run: CPU::nop,
    // },
    // Instruction {
    //     opcode: 251,
    //     name: "ISC",
    //     mode: AddrMode::AbsoluteY,
    //     size: 0,
    //     cycles: 7,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 252,
    //     name: "NOP",
    //     mode: AddrMode::AbsoluteX,
    //     size: 3,
    //     cycles: 4,
    //     page_cycles: 1,
    //     run: CPU::nop,
    // },
    // Instruction {
    //     opcode: 253,
    //     name: "SBC",
    //     mode: AddrMode::AbsoluteX,
    //     size: 3,
    //     cycles: 4,
    //     page_cycles: 1,
    // },
    // Instruction {
    //     opcode: 254,
    //     name: "INC",
    //     mode: AddrMode::AbsoluteX,
    //     size: 3,
    //     cycles: 7,
    //     page_cycles: 0,
    // },
    // Instruction {
    //     opcode: 255,
    //     name: "ISC",
    //     mode: AddrMode::AbsoluteX,
    //     size: 0,
    //     cycles: 7,
    //     page_cycles: 0,
    // },
];
