---
name: CI

# yamllint disable-line rule:truthy
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  format:
    name: Check format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: cargo fmt --all --check

  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        toolchain: [nightly]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
          targets: wasm32-unknown-unknown
          components: clippy
      - uses: Swatinem/rust-cache@v2
      - if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install libudev-dev libasound2-dev
      - run: |
          cargo clippy --all-targets
          cargo clippy --target wasm32-unknown-unknown
      - run: |
          cargo build -p tetanes
          cargo build -p tetanes --target wasm32-unknown-unknown
      - run: cargo doc
      - run: cargo test
