---
name: Check Outdated

# yamllint disable-line rule:truthy
on:
  schedule:
    # At 06:00 on day-of-month 2 and 16
    - cron: "0 6 2,16 * *"

env:
  CARGO_TERM_COLOR: always

jobs:
  outdated:
    name: Check Outdated
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: dtolnay/install@cargo-outdated
      - run: cargo outdated -e --exit-code 1
